apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks-stg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: helm-hooks-stg
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-hooks-stg
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
